"""create patients table

Revision ID: 37565f628cbc
Revises: 
Create Date: 2026-09-17 15:47:40.166340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37565f628cbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('age_recorded_on', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('referred_by', sa.String(length=150), nullable=True),
    sa.Column('current_medication', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'ta', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
