"""v3: roles, vitals, medicines, cards, investigations, appointments

Revision ID: 60e5d5002886
Revises: 37565f628cbc
Create Date: 2026-09-18 16:26:41.631132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '60e5d5002886'
down_revision: Union[str, Sequence[str], None] = '37565f628cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum types are created once here rather than inline on each column:
# 'language' already exists from the v2 patients migration, and 'templatekey'
# and 'language' are each used by two tables, so inline creation would emit
# CREATE TYPE more than once and fail.
ENUM_TYPES = {
    "role": ("doctor", "reception", "pharmacy"),
    "uilanguage": ("en", "ta"),
    "language": ("en", "ta"),
    "templatekey": (
        "welcome", "recall", "appointment_confirmation",
        "appointment_reminder", "medicine_dispatched", "review_request",
    ),
    "messagechannel": ("whatsapp_manual", "whatsapp_api", "sms"),
    "appointmentstatus": ("booked", "attended", "cancelled", "no_show"),
    "visitstatus": ("waiting", "in_consultation", "completed"),
    "visitsource": ("recorded", "migrated"),
    "investigationkind": ("scan", "lab", "xray", "ecg", "other"),
    "paymentmode": ("cash", "upi"),
    "medicineform": ("pills", "drops"),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an existing type without trying to create it again."""
    return postgresql.ENUM(*ENUM_TYPES[name], name=name, create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for name, values in ENUM_TYPES.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', _enum('role'), nullable=False),
    sa.Column('ui_language', _enum('uilanguage'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ta', sa.String(length=120), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_ta', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('clinic_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=False),
    sa.Column('doctor_qualifications', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('landmark', sa.Text(), nullable=False),
    sa.Column('map_link', sa.Text(), nullable=False),
    sa.Column('working_hours', sa.Text(), nullable=False),
    sa.Column('review_link', sa.Text(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('default_consultation_fee', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_templates',
    sa.Column('template_key', _enum('templatekey'), nullable=False),
    sa.Column('language', _enum('language'), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_key', 'language')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', _enum('appointmentstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('template_key', _enum('templatekey'), nullable=False),
    sa.Column('language', _enum('language'), nullable=False),
    sa.Column('channel', _enum('messagechannel'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_by_user_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_patient_id'), 'message_log', ['patient_id'], unique=False)
    op.create_index(op.f('ix_message_log_sent_at'), 'message_log', ['sent_at'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('next_visit_due', sa.Date(), nullable=True),
    sa.Column('status', _enum('visitstatus'), nullable=False),
    sa.Column('source', _enum('visitsource'), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_next_visit_due'), 'visits', ['next_visit_due'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_visit_date'), 'visits', ['visit_date'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('kind', _enum('investigationkind'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_patient_id'), 'investigations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_investigations_title'), 'investigations', ['title'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('consultation_fee', sa.Integer(), nullable=False),
    sa.Column('medicine_charge', sa.Integer(), nullable=False),
    sa.Column('payment_mode', _enum('paymentmode'), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('visit_medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('potency', sa.String(length=30), nullable=True),
    sa.Column('form', _enum('medicineform'), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_medicines_visit_id'), 'visit_medicines', ['visit_id'], unique=False)
    op.create_table('visit_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_photos_visit_id'), 'visit_photos', ['visit_id'], unique=False)
    op.create_table('visit_vitals',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('investigation_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_files_investigation_id'), 'investigation_files', ['investigation_id'], unique=False)
    op.add_column('patients', sa.Column('migrated_from_myopd', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'migrated_from_myopd')
    op.drop_index(op.f('ix_investigation_files_investigation_id'), table_name='investigation_files')
    op.drop_table('investigation_files')
    op.drop_table('visit_vitals')
    op.drop_index(op.f('ix_visit_photos_visit_id'), table_name='visit_photos')
    op.drop_table('visit_photos')
    op.drop_index(op.f('ix_visit_medicines_visit_id'), table_name='visit_medicines')
    op.drop_table('visit_medicines')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_investigations_title'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_patient_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_visits_visit_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_next_visit_due'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_message_log_sent_at'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_patient_id'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('message_templates')
    op.drop_table('clinic_profile')
    op.drop_table('cards')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###

    # 'language' is deliberately excluded: it predates this migration and the
    # patients table still uses it. Dropping it here would break v2.
    bind = op.get_bind()
    for name in ENUM_TYPES:
        if name == "language":
            continue
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
